workers_dev = true
name = "my-worker"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id"
migrations_dir = "migration/sqlite"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-id"

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare Vars"